### ISSUE TITLE
deleted_at should be blank

### ISSUE THREAD

**Issue by fglaria** [xgeekshq/django-timestamps#6]
When calling `full_clean()` before `save()`, it throws an exception:

```shell
django.core.exceptions.ValidationError: {'deleted_at': ['This field cannot be blank.']]}
```

This is fixed if in `SoftDeletes` model, to its attribute `deleted_at` you add the `blank=True` option.

**Comment by dmp593** [comment]
Hi @fglaria!

I think this issue is solved here https://github.com/xgeekshq/django-timestampable/commit/2df37900bd10ded56819a3baaf9fa4f7b973cb6b#diff-f9e2f222c633d2e17e2b2e80e2173e6169b5715242fff9118e783a83a20b8716

Thank you for the suggestion 😊

**Comment by fglaria** [comment]
Great!
